name: heron
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  # 路由管理
  go_router: ^15.2.0
  #国际化
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  #状态管理
  flutter_riverpod: ^2.6.1
  #数据的存储 本地存储持久化数据
  shared_preferences: ^2.5.3
  shared_preferences_web: ^2.4.3
  # 网络
  dio: ^5.8.0+1
  web_socket_channel: ^3.0.3
  flutter_svg: ^2.2.0
  lottie: ^3.3.1
  # 平台特定工具，用于 Canvas 指纹识别和设备信息
  device_info_plus: ^11.5.0
  # 用于判断应用运行在 Web、Android、iOS 等平台
  universal_platform: ^1.1.0
  #在 Dart 中访问 Web DOM 所需（例如 Canvas）
  web: ^1.1.1
  crypto: ^3.0.6

  #日志
  logger: ^2.5.0

  flutter_inappwebview: ^6.1.5
  pointer_interceptor: ^0.10.1+2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  json_serializable: ^6.9.5

flutter:
  generate: true
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

